// A javascript-enhanced crossword puzzle [c] Jesse Weisbeck, MIT/GPL
(function($) {
  $(function() {
    // provide crossword entries in an array of objects like the following example
    // Position refers to the numerical order of an entry. Each position can have
    // two entries: an across entry and a down entry
    var puzzleData = [
      {
        clue: 'Two rays with the same endpoint or vertex',
        answer: 'angle',
        position: 1,
        orientation: 'across',
        startx: 1,
        starty: 1
      }, {
        clue: 'What is the other name of Graduate Women in Science, formed in 1921',
        answer: 'delta',
        position: 3,
        orientation: 'across',
        startx: 7,
        starty: 1
      }, {
        clue: 'Won two noble prizes and discovered two elements while working in the field of radioactivity',
        answer: 'curie',
        position: 5,
        orientation: 'across',
        startx: 1,
        starty: 3
      }, {
        clue: 'The set of all whole numbers and their opposites.',
        answer: 'integer',
        position: 8,
        orientation: 'across',
        startx: 1,
        starty: 5
      }, {
        clue: 'Complex resistances',
        answer: 'impedances',
        position: 10,
        orientation: 'across',
        startx: 2,
        starty: 7
      }, {
        clue: 'This device is used to step-up, step-down, and/or isolate',
        answer: 'transformer',
        position: 13,
        orientation: 'across',
        startx: 1,
        starty: 9
      }, {
        clue: 'Type of ray emitted from the sun',
        answer: 'gamma',
        position: 16,
        orientation: 'across',
        startx: 1,
        starty: 11
      }, {
        clue: 'C programming language operator',
        answer: 'cysan',
        position: 17,
        orientation: 'across',
        startx: 7,
        starty: 11
      }, {
        clue: '(American Standard Code for Information Interchange) An early and very basic format for text files, standard across pretty much all computers and mail systems. It only includes upper and lower case letters, numbers, and standard punctuation marks, but more sophisticated text formats still tend to be based on it. An ASCII file is a basic text-only file generated by a program like Notepad.',
        answer: 'ascii',
        position: 1,
        orientation: 'down',
        startx: 1,
        starty: 1
      }, {
        clue: '(EXEcutable; pr. "exie", "dot exie" ) A file which is usually the main part of a program. A program may consist of just an exe file and nothing else, or there may be dozens of files, including more exes.',
        answer: 'exe',
        position: 2,
        orientation: 'down',
        startx: 5,
        starty: 1
      }, {
        clue: 'A rival PC operating system to Microsoft Windows, but unlike Windows it is "open source", which means that anyone can create their own version of it without having to pay royalties, and requires a much less powerful computer. Initially required a lot of technical knowledge, but is rapidly being made much more user-friendly.',
        answer: 'linux',
        position: 4,
        orientation: 'down',
        startx: 9,
        starty: 1
      }, {
        clue: 'A program that has been deliberately created to cause computer problems, usually minor ones as a prank, but occasionally very nasty ones indeed, such as erasing your entire hard disk. Viruses were originally designed to attach themselves to programs on a disk, and then "hide" in the computers memory once the host program is executed, and "infect" every disk they come across. Some types of virus (such as the famous "I love you") propagate by email, disguised as an attachment, which is why you should never open an attachment you are unsure of.',
        answer: 'virus',
        position: 6,
        orientation: 'down',
        startx: 7,
        starty: 3
      }, {
        clue: '(Video Graphics Array) An early colour graphics standard for PCs, now used as a sort of lowest common denominator which all monitors and graphics cards understand.',
        answer: 'vga',
        position: 7,
        orientation: 'down',
        startx: 11,
        starty: 3
      }, {
        clue: 'Coined the term bug _____ Hopper',
        answer: 'grace',
        position: 9,
        orientation: 'down',
        startx: 5,
        starty: 5
      }, {
        clue: 'Emits a lout wailing sound',
        answer: 'siren',
        position: 11,
        orientation: 'down',
        startx: 11,
        starty: 7
      }, {
        clue: 'Information technology (abbr.)',
        answer: 'it',
        position: 12,
        orientation: 'down',
        startx: 1,
        starty: 8
      }, {
        clue: 'Asynchronous transfer mode (abbr.)',
        answer: 'atm',
        position: 14,
        orientation: 'down',
        startx: 3,
        starty: 9
      }, {
        clue: 'Offset current control (abbr.)',
        answer: 'occ',
        position: 15,
        orientation: 'down',
        startx: 7,
        starty: 9
      }
    ];

    $('#puzzle-wrapper').crossword(puzzleData);
  })
})(jQuery)
